import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter"
});
const geistSans = Inter({
  subsets: ["latin"],
  variable: "--font-geist-sans",
  weight: ["400", "700"]
});
const geistMono = Inter({
  subsets: ["latin"],
  variable: "--font-geist-mono",
  weight: ["400", "700"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
